/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterAccountCommand"];
                    "text/json": components["schemas"]["RegisterAccountCommand"];
                    "application/*+json": components["schemas"]["RegisterAccountCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RegisterAccountResult"];
                        "application/json": components["schemas"]["RegisterAccountResult"];
                        "text/json": components["schemas"]["RegisterAccountResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                    "text/json": components["schemas"]["ChangePasswordRequest"];
                    "application/*+json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginCommand"];
                    "text/json": components["schemas"]["LoginCommand"];
                    "application/*+json": components["schemas"]["LoginCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResult"];
                        "application/json": components["schemas"]["LoginResult"];
                        "text/json": components["schemas"]["LoginResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BotResult"][];
                        "application/json": components["schemas"]["BotResult"][];
                        "text/json": components["schemas"]["BotResult"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateBotRequest"];
                    "text/json": components["schemas"]["CreateBotRequest"];
                    "application/*+json": components["schemas"]["CreateBotRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateBotResult"];
                        "application/json": components["schemas"]["CreateBotResult"];
                        "text/json": components["schemas"]["CreateBotResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BotTokenResult"];
                        "application/json": components["schemas"]["BotTokenResult"];
                        "text/json": components["schemas"]["BotTokenResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChatResult"][];
                        "application/json": components["schemas"]["ChatResult"][];
                        "text/json": components["schemas"]["ChatResult"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChatResult"];
                        "application/json": components["schemas"]["ChatResult"];
                        "text/json": components["schemas"]["ChatResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/direct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateDirectChatRequest"];
                    "text/json": components["schemas"]["CreateDirectChatRequest"];
                    "application/*+json": components["schemas"]["CreateDirectChatRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateChatResult"];
                        "application/json": components["schemas"]["CreateChatResult"];
                        "text/json": components["schemas"]["CreateChatResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateGroupChatRequest"];
                    "text/json": components["schemas"]["CreateGroupChatRequest"];
                    "application/*+json": components["schemas"]["CreateGroupChatRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateChatResult"];
                        "application/json": components["schemas"]["CreateChatResult"];
                        "text/json": components["schemas"]["CreateChatResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddChatMemberRequest"];
                    "text/json": components["schemas"]["AddChatMemberRequest"];
                    "application/*+json": components["schemas"]["AddChatMemberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/members/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangeChatMemberRoleRequest"];
                    "text/json": components["schemas"]["ChangeChatMemberRoleRequest"];
                    "application/*+json": components["schemas"]["ChangeChatMemberRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MarkChatReadRequest"];
                    "text/json": components["schemas"]["MarkChatReadRequest"];
                    "application/*+json": components["schemas"]["MarkChatReadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    after?: number;
                    before?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageResult"][];
                        "application/json": components["schemas"]["MessageResult"][];
                        "text/json": components["schemas"]["MessageResult"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                    "text/json": components["schemas"]["SendMessageRequest"];
                    "application/*+json": components["schemas"]["SendMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SendMessageResult"];
                        "application/json": components["schemas"]["SendMessageResult"];
                        "text/json": components["schemas"]["SendMessageResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/messages/wait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    after: number;
                    from?: string;
                    replyTo?: number;
                    timeout?: number;
                };
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WaitForMessagesResult"];
                        "application/json": components["schemas"]["WaitForMessagesResult"];
                        "text/json": components["schemas"]["WaitForMessagesResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/messages/{seq}/attachments/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                    seq: number;
                    fileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UploadFileResult"];
                        "application/json": components["schemas"]["UploadFileResult"];
                        "text/json": components["schemas"]["UploadFileResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MeResult"];
                        "application/json": components["schemas"]["MeResult"];
                        "text/json": components["schemas"]["MeResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfileResult"];
                        "application/json": components["schemas"]["ProfileResult"];
                        "text/json": components["schemas"]["ProfileResult"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                    "text/json": components["schemas"]["UpdateProfileRequest"];
                    "application/*+json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccessTokenResult"][];
                        "application/json": components["schemas"]["AccessTokenResult"][];
                        "text/json": components["schemas"]["AccessTokenResult"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IssueTokenRequest"];
                    "text/json": components["schemas"]["IssueTokenRequest"];
                    "application/*+json": components["schemas"]["IssueTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IssuedAccessTokenResult"];
                        "application/json": components["schemas"]["IssuedAccessTokenResult"];
                        "text/json": components["schemas"]["IssuedAccessTokenResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tokenId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    query: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserSearchResult"][];
                        "application/json": components["schemas"]["UserSearchResult"][];
                        "text/json": components["schemas"]["UserSearchResult"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessTokenResult: {
            /** Format: uuid */
            tokenId: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        AccountType: "User" | "Bot";
        AddChatMemberRequest: {
            /** Format: uuid */
            userId: string;
        };
        /** @enum {string} */
        AttachmentKind: "File" | "Image" | "Voice";
        AttachmentResult: {
            /** Format: uuid */
            fileId: string;
            kind: components["schemas"]["AttachmentKind"];
            fileName: string;
            contentType: string;
            /** Format: int64 */
            size: number;
            /** Format: int32 */
            durationSeconds?: number | null;
            transcript?: components["schemas"]["TranscriptResult"] | null;
        };
        BotResult: {
            /** Format: uuid */
            botId: string;
            displayName?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        BotTokenResult: {
            /** Format: uuid */
            botId: string;
            token: string;
        };
        ChangeChatMemberRoleRequest: {
            role?: components["schemas"]["ChatRole"] | null;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        ChatMemberResult: {
            /** Format: uuid */
            userId: string;
            displayName?: string | null;
            isBot: boolean;
            role: components["schemas"]["ChatRole"];
            /** Format: date-time */
            joinedAt: string;
        };
        ChatResult: {
            /** Format: uuid */
            chatId: string;
            type: components["schemas"]["ChatType"];
            title?: string | null;
            members: components["schemas"]["ChatMemberResult"][];
            /** Format: int64 */
            lastMessageSeq: number;
            /** Format: date-time */
            lastMessageAt?: string | null;
            /** Format: int64 */
            lastReadSeq: number;
            /** Format: int64 */
            unreadCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        ChatRole: "Owner" | "Admin" | "Member";
        /** @enum {string} */
        ChatType: "Direct" | "Group";
        CreateBotRequest: {
            displayName: string;
        };
        CreateBotResult: {
            /** Format: uuid */
            botId: string;
            token: string;
        };
        CreateChatResult: {
            /** Format: uuid */
            chatId: string;
        };
        CreateDirectChatRequest: {
            /** Format: uuid */
            userId: string;
        };
        CreateGroupChatRequest: {
            title: string;
            memberIds?: string[] | null;
        };
        IssueTokenRequest: {
            name: string;
        };
        IssuedAccessTokenResult: {
            /** Format: uuid */
            tokenId: string;
            name: string;
            token: string;
            /** Format: date-time */
            createdAt: string;
        };
        LoginCommand: {
            email: string;
            password: string;
        };
        LoginResult: {
            /** Format: uuid */
            accountId: string;
            accessToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        MarkChatReadRequest: {
            /** Format: int64 */
            seq?: number | null;
        };
        MeResult: {
            /** Format: uuid */
            accountId: string;
            type: components["schemas"]["AccountType"];
            isBot: boolean;
            email?: string | null;
            /** Format: uuid */
            ownerId?: string | null;
            profile?: components["schemas"]["ProfileResult"] | null;
        };
        MessageResult: {
            /** Format: uuid */
            messageId: string;
            /** Format: uuid */
            chatId: string;
            /** Format: int64 */
            seq: number;
            /** Format: uuid */
            authorId: string;
            authorName?: string | null;
            authorIsBot: boolean;
            text?: string | null;
            attachments: components["schemas"]["AttachmentResult"][];
            /** Format: int64 */
            replyToSeq?: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        ProfileResult: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /** Format: uuid */
            avatarId?: string | null;
            bio?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        RegisterAccountCommand: {
            email: string;
            password: string;
        };
        RegisterAccountResult: {
            /** Format: uuid */
            accountId: string;
        };
        SendMessageRequest: {
            text?: string | null;
            fileIds?: string[] | null;
            voice?: components["schemas"]["SendVoiceRequest"] | null;
            /** Format: int64 */
            replyToSeq?: number | null;
        };
        SendMessageResult: {
            /** Format: uuid */
            messageId: string;
            /** Format: uuid */
            chatId: string;
            /** Format: int64 */
            seq: number;
            /** Format: date-time */
            createdAt: string;
        };
        SendVoiceRequest: {
            /** Format: uuid */
            fileId: string;
            /** Format: int32 */
            durationSeconds: number;
        };
        TranscriptResult: {
            status: components["schemas"]["TranscriptStatus"];
            text?: string | null;
        };
        /** @enum {string} */
        TranscriptStatus: "None" | "Pending" | "Done" | "Failed";
        UpdateProfileRequest: {
            displayName: string;
            bio?: string | null;
        };
        UploadFileResult: {
            /** Format: uuid */
            fileId: string;
            fileName: string;
            contentType: string;
            /** Format: int64 */
            size: number;
        };
        UserSearchResult: {
            /** Format: uuid */
            userId: string;
            displayName?: string | null;
            isBot: boolean;
        };
        WaitForMessagesResult: {
            messages: components["schemas"]["MessageResult"][];
            /** Format: int64 */
            nextAfterSeq: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
