@MessengerWeb_HostAddress = http://localhost:5243

POST {{MessengerWeb_HostAddress}}/api/users/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "P@ssw0rd!",
  "displayName": "Test User"
}

###
